"""Phase L fixtures — relevant facet selection evaluation. Not a Reasoning Core."""
from __future__ import annotations

from typing import Any

# Catalog tags live on the fixture record. Selection is alias/token overlap, not inference.
FACET_CATALOG: list[dict[str, Any]] = [
    {
        "facet_id": "control_authority",
        "family": "robot",
        "aliases": [
            "control authority",
            "操作権",
            "remote control",
            "local control",
            "teach pendant",
            "外部制御",
            "人間が",
        ],
        "evidence": ["ISO 10218-1:2011 5.3.5", "UR SW5_20 Remote Control"],
        "unknown": ["Non-UR vendors not live-tested"],
        "conflicts": ["KUKA EXT vs UR split Automatic/Remote"],
    },
    {
        "facet_id": "operational_mode",
        "family": "robot",
        "aliases": ["operational mode", "automatic", "manual", "運転モード", "AUTOMATIC"],
        "evidence": ["Dashboard get operational mode"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "operational_mode_source",
        "family": "robot",
        "aliases": [
            "operational mode source",
            "mode source",
            "set operational mode",
            "clear operational mode",
            "dashboard",
            "ownership",
        ],
        "pull_with": ["operational_mode"],
        "evidence": ["J-1 AUTOMATIC remains after TCP close", "clear operational mode → NONE"],
        "unknown": [],
        "conflicts": ["Not the same lock as Remote Control"],
    },
    {
        "facet_id": "transport",
        "family": "robot",
        "aliases": ["tcp", "切断", "通信を切断", "disconnect", "dashboardとのtcp", "接続"],
        "evidence": ["J-1 TCP close per command; lock remains"],
        "unknown": [],
        "conflicts": ["transport-vs-authority: TCP disconnect does not clear operational mode"],
    },
    {
        "facet_id": "controller_state",
        "family": "robot",
        "aliases": ["controller state", "robotmode", "controller"],
        "evidence": ["Dashboard robotmode"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "program_state",
        "family": "robot",
        "aliases": ["program state", "programstate", "実行可能", "play", "program"],
        "evidence": ["Dashboard programstate STOPPED ≠ executed"],
        "unknown": [],
        "conflicts": ["accept-vs-execute"],
    },
    {
        "facet_id": "safety_state",
        "family": "robot",
        "aliases": ["safety", "安全に", "safetymode", "protective"],
        "evidence": [],
        "unknown": ["Protective Stop transitions not measured on this URSim session"],
        "conflicts": [],
    },
    {
        "facet_id": "human_handoff",
        "family": "robot",
        "aliases": [
            "handoff",
            "再開",
            "polyscope",
            "人間が",
            "human review",
            "操作を再開",
        ],
        "evidence": ["HUMAN_CONTROL_OWNERSHIP", "clear operational mode then PolyScope confirm"],
        "unknown": ["J-2 human simulation not PASS"],
        "conflicts": ["TCP disconnect ≠ human handoff"],
    },
    {
        "facet_id": "urscript_api",
        "family": "robot",
        "aliases": ["urscript", "ur script", "dashboard server", "api"],
        "evidence": ["Dashboard load/play; Secondary Client"],
        "unknown": [".script load failed in Phase I-Live"],
        "conflicts": [],
    },
    {
        "facet_id": "execution_observation",
        "family": "robot",
        "aliases": ["execution observation", "実行", "observation", "3d"],
        "evidence": ["Command response ≠ motion observation"],
        "unknown": ["J-2/J-8 live play not measured"],
        "conflicts": [],
    },
    {
        "facet_id": "ursim",
        "family": "env",
        "aliases": ["ursim", "ursim 5.15.2", "polyscope gui"],
        "evidence": ["universalrobots/ursim_e-series:5.15 VERSION 5.15.2"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "version",
        "family": "version",
        "aliases": ["5.15.2", "5.17", "version", "バージョン"],
        "evidence": ["ursim_version 5.15.2"],
        "unknown": [],
        "conflicts": ["5.17 Security/Permission is not applied to 5.15.2"],
    },
    {
        "facet_id": "source_version",
        "family": "version",
        "aliases": ["source version", "sw5_20", "release notes", "5.17.x"],
        "evidence": ["SW5_20 Remote Control; 5.17 notes labeled does_not_apply"],
        "unknown": [],
        "conflicts": ["ISO-2011-vs-2025"],
    },
    {
        "facet_id": "permission_feature",
        "family": "version",
        "aliases": ["permission", "security", "権限", "5.17"],
        "evidence": ["5.17 permission model recorded as not applying to 5.15.2"],
        "unknown": ["Whether 5.17 Security/Permission restrictions exist on 5.15.2"],
        "conflicts": ["do not mix 5.17 into 5.15.2"],
    },
    {
        "facet_id": "cycle_controller",
        "family": "robot",
        "aliases": ["cycle", "n回", "外部トリガ", "external trigger", "counted"],
        "evidence": ["Yaskawa SetCycleMode; UR Dashboard counted cycle not found"],
        "unknown": ["Whether UR 5.15.2 exposes a first-class counted controller cycle"],
        "conflicts": ["LLM for-loop vs controller cycle"],
    },
    {
        "facet_id": "docker",
        "family": "env",
        "aliases": ["docker", "docker engine", "docker環境", "コンテナ"],
        "pull_with": ["wsl2", "storage", "network_ports"],
        "evidence": ["ai_agent_ursim_phase_i container"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "wsl2",
        "family": "env",
        "aliases": ["wsl2", "wsl"],
        "evidence": ["Docker Desktop WSL data folder"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "cpu_virtualization",
        "family": "env",
        "aliases": ["virtualization", "仮想化", "vt-x"],
        "evidence": [],
        "unknown": ["CPU virtualization not re-probed this phase"],
        "conflicts": [],
    },
    {
        "facet_id": "ram",
        "family": "env",
        "aliases": ["ram", "メモリ"],
        "evidence": [],
        "unknown": ["RAM headroom not recorded on this fixture"],
        "conflicts": [],
    },
    {
        "facet_id": "storage",
        "family": "env",
        "aliases": ["storage", "disk", "d:\\dockerdesktopwsl"],
        "evidence": ["Docker disk D:\\DockerDesktopWSL"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "network_ports",
        "family": "env",
        "aliases": ["ports", "6080", "29999", "ポート", "network"],
        "evidence": ["noVNC 6080 Dashboard 29999"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "python_version",
        "family": "oss",
        "aliases": ["python", "python 3.12"],
        "evidence": ["not used for URSim 5.15.2 controller ownership"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "cuda",
        "family": "oss",
        "aliases": ["cuda", "cuda 12"],
        "evidence": [],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "license",
        "family": "oss",
        "aliases": ["license", "mit", "gpl", "ライセンス"],
        "evidence": [],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "documentation_version",
        "family": "oss",
        "aliases": ["documentation version", "docs version"],
        "evidence": [],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "gpu",
        "family": "oss",
        "aliases": ["gpu", "rtx", "nvidia"],
        "evidence": [],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "cpu",
        "family": "oss",
        "aliases": ["cpu", "intel", "i5"],
        "evidence": [],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "evidence",
        "family": "meta",
        "aliases": ["evidence", "根拠", "出典"],
        "evidence": ["sources[] on ResearchRecord"],
        "unknown": [],
        "conflicts": [],
    },
    {
        "facet_id": "conflict",
        "family": "meta",
        "aliases": ["conflict", "競合", "混ぜ"],
        "evidence": [],
        "unknown": [],
        "conflicts": ["5.17 vs 5.15.2"],
    },
]

OSS_IRRELEVANT = [
    "python_version",
    "cuda",
    "license",
    "documentation_version",
    "gpu",
    "cpu",
]

CASES: list[dict[str, Any]] = [
    {
        "id": "L2",
        "requirement": (
            "URSimをAgentから操作したあと、人間がPolyScopeから安全に操作を再開できるようにしたい"
        ),
        "expected": [
            "control_authority",
            "operational_mode",
            "operational_mode_source",
            "transport",
            "controller_state",
            "program_state",
            "safety_state",
            "human_handoff",
        ],
        "irrelevant": list(OSS_IRRELEVANT),
        "why_expected": {
            "control_authority": "誰がペンダント操作できるかが要求の本体",
            "operational_mode": "Automatic ロックが人間操作を阻む",
            "operational_mode_source": "Dashboard 所有は切断では消えない",
            "transport": "Agent 操作後の通信切断がよく同時に語られる",
            "controller_state": "再開可能かは robotmode にも依存",
            "program_state": "実行中 Program の有無",
            "safety_state": "安全に再開",
            "human_handoff": "人間が PolyScope から再開",
        },
    },
    {
        "id": "L3",
        "requirement": "人間がPolyScopeから操作を再開できるか",
        "expected": ["human_handoff", "control_authority"],
        "irrelevant": list(OSS_IRRELEVANT),
        "why_expected": {
            "human_handoff": "再開・PolyScope",
            "control_authority": "操作できる主体",
        },
    },
    {
        "id": "L4-A",
        "requirement": "DashboardとのTCP接続を切断すれば、人間が操作権を取り戻せるか？",
        "expected": [
            "transport",
            "control_authority",
            "operational_mode",
            "operational_mode_source",
            "human_handoff",
        ],
        "irrelevant": list(OSS_IRRELEVANT) + ["cuda", "python_version"],
        "why_expected": {
            "transport": "TCP切断が条件",
            "control_authority": "操作権",
            "operational_mode": "所有されている mode 値",
            "operational_mode_source": "誰が mode を握るか",
            "human_handoff": "人間が取り戻せるか",
        },
    },
    {
        "id": "L4-B",
        "requirement": "URScriptがURSim 5.15.2で実行可能か？",
        "expected": ["urscript_api", "version", "ursim", "program_state", "execution_observation"],
        "irrelevant": list(OSS_IRRELEVANT),
        "not_primary": ["control_authority"],
        "why_expected": {
            "urscript_api": "URScript",
            "version": "5.15.2",
            "ursim": "URSim",
            "program_state": "実行可能",
            "execution_observation": "実行の観測",
        },
    },
    {
        "id": "L4-C",
        "requirement": "URSim 5.15.2をこのPC環境で起動できるか？",
        "expected": [
            "ursim",
            "version",
            "docker",
            "wsl2",
            "cpu_virtualization",
            "ram",
            "storage",
            "network_ports",
        ],
        "irrelevant": ["control_authority", "human_handoff"] + OSS_IRRELEVANT,
        "why_expected": {
            "ursim": "URSim",
            "version": "5.15.2",
            "docker": "本環境の起動経路",
            "wsl2": "Docker Desktop",
            "cpu_virtualization": "PC環境",
            "ram": "PC環境",
            "storage": "PC環境",
            "network_ports": "起動後ポート",
        },
    },
    {
        "id": "L4-D",
        "requirement": "5.17のPermission仕様を5.15.2へ適用できるか？",
        "expected": ["version", "source_version", "permission_feature", "evidence", "conflict"],
        "irrelevant": list(OSS_IRRELEVANT) + ["human_handoff"],
        "why_expected": {
            "version": "5.15.2 と 5.17",
            "source_version": "資料世代",
            "permission_feature": "Permission",
            "evidence": "根拠の帰属",
            "conflict": "無条件適用禁止",
        },
    },
    {
        "id": "L6",
        "requirement": "このControllerで外部トリガによるN回Cycleを安全に実行できますか？",
        "expected": ["cycle_controller", "safety_state"],
        "irrelevant": list(OSS_IRRELEVANT),
        "require_unknown": ["cycle_controller", "safety_state"],
        "why_expected": {
            "cycle_controller": "N回 Cycle / 外部トリガ",
            "safety_state": "安全に",
        },
    },
    {
        "id": "L7",
        "requirement": "5.15.2でBのPermission仕様を使えるか？",
        "expected": ["version", "permission_feature", "conflict", "source_version"],
        "irrelevant": list(OSS_IRRELEVANT),
        "require_conflict": True,
        "why_expected": {
            "version": "5.15.2",
            "permission_feature": "Permission仕様 B",
            "conflict": "5.17 を 5.15.2 へ混ぜない",
            "source_version": "Source B は 5.17.x",
        },
    },
    {
        "id": "L8",
        "requirement": "以前調べたURSim 5.15.2について、今度はDocker環境だけ詳しく調べたい",
        "expected": ["ursim", "version", "docker", "wsl2", "network_ports"],
        "irrelevant": ["control_authority", "human_handoff"] + OSS_IRRELEVANT,
        "reuse_present_on_record": ["ursim", "version", "docker", "wsl2", "network_ports"],
        "fresh_research_ok": ["cpu_virtualization", "ram"],
        "why_expected": {
            "ursim": "URSim",
            "version": "5.15.2",
            "docker": "Docker環境だけ",
            "wsl2": "Docker 実行基盤",
            "network_ports": "環境の一部",
        },
    },
    {
        "id": "L9",
        "requirement": (
            "URSimをAgentから操作したあと、Dashboardとの通信を切断すれば、"
            "人間がPolyScopeから安全に操作を再開できるToolを作ってください。"
        ),
        "expected": [
            "transport",
            "control_authority",
            "operational_mode",
            "operational_mode_source",
            "human_handoff",
        ],
        "irrelevant": list(OSS_IRRELEVANT),
        "require_conflict_id": "transport-vs-authority",
        "why_expected": {
            "transport": "通信を切断",
            "control_authority": "人間操作",
            "operational_mode": "残存 AUTOMATIC",
            "operational_mode_source": "Dashboard 所有",
            "human_handoff": "PolyScope から再開",
        },
    },
]


def record_with_catalog() -> dict[str, Any]:
    """Past research envelope: Phase J robot facts + OSS noise + env facts."""
    return {
        "research_id": "RR-phase-l-facet-catalog",
        "requirement": (
            "When an Agent or Tool drives an industrial robot controller, separate "
            "transport, control authority, and human handoff. Do not treat Dashboard "
            "TCP disconnect as ownership release."
        ),
        "topic": "Industrial robot Control Authority and URSim 5.15.2 environment",
        "technology_candidates": [
            {
                "candidate_id": "UR-5152",
                "name": "Universal Robots PolyScope / Dashboard Server",
                "type": "Vendor controller",
                "version": "5.15.2",
                "environment": {"python": "Python 3.12", "cuda": "CUDA 12", "os": "Windows"},
                "license": "UNKNOWN",
                "source_category": "Official Documentation",
                "source_title": "Dashboard / Remote Control",
                "url": "https://www.universal-robots.com/manuals/EN/HTML/SW5_20/",
                "unknowns": [
                    "Whether UR 5.15.2 exposes a first-class counted controller cycle",
                    "Protective Stop transitions not measured on this URSim session",
                ],
                "conflicts": [
                    {
                        "id": "transport-vs-authority",
                        "note": "TCP disconnect does not clear UR operational mode ownership (J-1).",
                    },
                    {
                        "id": "v517-vs-v515",
                        "note": "5.17 Permission/Security is not applied to 5.15.2.",
                    },
                ],
            }
        ],
        "version_facts": [
            {
                "technology": "URSim",
                "version": "5.15.2",
                "python": "Python 3.12",
                "cuda": "CUDA 12",
                "os": "Windows",
                "applies_to": "5.15.2",
                "does_not_apply": "PolyScope 5.17 default security / System admin lock",
            }
        ],
        "environment_facts": {
            "ursim_version": "5.15.2",
            "docker": "ai_agent_ursim_phase_i",
            "wsl2": "DockerDesktopWSL",
            "network_ports": "6080,29999",
            "python": "Python 3.12",
            "cuda": "CUDA 12",
            "gpu": "RTX 3060",
            "cpu": "i5-12400",
            "operational_mode": "AUTOMATIC",
            "transport": "disconnected",
            "simulation_state": "UNKNOWN",
        },
        "license_facts": ["UNKNOWN"],
        "unknowns": [
            "Whether UR 5.15.2 exposes a first-class counted controller cycle",
            "Protective Stop transitions not measured on this URSim session",
            "RAM headroom not recorded on this fixture",
            "CPU virtualization not re-probed this phase",
        ],
        "conflicts": [
            {
                "id": "transport-vs-authority",
                "summary": "TCP disconnect does not clear UR operational mode ownership (J-1).",
            },
            {
                "id": "v517-vs-v515",
                "summary": "5.17 Permission/Security is not applied to 5.15.2.",
            },
        ],
        "facet_records": FACET_CATALOG,
        "checked_at": "2026-08-30T07:00:00+00:00",
        "queries": [],
        "api_observations": [],
        "sources": [],
        "provenance": "phase_l_fixture",
    }
